### PR TITLE
Add tests for packages that use mod-standard

### LINKED ISSUE #5: Test project
We should pick a project that is known to be passing modulus standard, and write a test to ensure this project runs against it correctly. It will need to be open source, candidates:
- [x] [logger](https://github.com/onmodulus/logger)
- [x] [knock-knock](https://github.com/onmodulus/knock-knock)
- [ ] [demeteorizer](https://github.com/onmodulus/demeteorizer)
- [x] [get-version](https://github.com/onmodulus/get-version)

### PR DESCRIPTION
**Pull request by jackboberg**
Closes #5

### CODE REVIEW

**Comment by jackboberg** [comment]
Moved cf42435 to a separate PR #8

**Comment by tzmanics** [comment]
:+1:

**Comment by jackboberg** [comment]
I actually decided I need to remove `mod-standard` from the test list, since it's a circular dependency. Any update to this package will end up being tested against the non-updated version of this package: eg: probably almost always fail. I'll rebase, but appreciate :+1: in advance.

**Comment by jackboberg** [comment]
Rebased, now passing with three remote projects.

**Comment by franvarney** [comment]
:neckbeard:

**Pull request merged**
